// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUuPUM1wUZiuxrZhk1B3_vww_lyhoBbA8',
    appId: '1:841226058427:web:370adf344467c6655fc79e',
    messagingSenderId: '841226058427',
    projectId: 'flutter-2a477',
    authDomain: 'flutter-2a477.firebaseapp.com',
    storageBucket: 'flutter-2a477.firebasestorage.app',
    measurementId: 'G-53B5N5G1B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXcKxPEVu8owOfUqdhwDg0X1m8NT1B3x8',
    appId: '1:841226058427:android:254b69cfeab9767d5fc79e',
    messagingSenderId: '841226058427',
    projectId: 'flutter-2a477',
    storageBucket: 'flutter-2a477.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe1JJ84phivPsZNA-TdxSPINX6lzlJSj4',
    appId: '1:841226058427:ios:59576591924768405fc79e',
    messagingSenderId: '841226058427',
    projectId: 'flutter-2a477',
    storageBucket: 'flutter-2a477.firebasestorage.app',
    iosBundleId: 'com.example.metrogo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe1JJ84phivPsZNA-TdxSPINX6lzlJSj4',
    appId: '1:841226058427:ios:59576591924768405fc79e',
    messagingSenderId: '841226058427',
    projectId: 'flutter-2a477',
    storageBucket: 'flutter-2a477.firebasestorage.app',
    iosBundleId: 'com.example.metrogo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUuPUM1wUZiuxrZhk1B3_vww_lyhoBbA8',
    appId: '1:841226058427:web:d60df0ae285dd7e05fc79e',
    messagingSenderId: '841226058427',
    projectId: 'flutter-2a477',
    authDomain: 'flutter-2a477.firebaseapp.com',
    storageBucket: 'flutter-2a477.firebasestorage.app',
    measurementId: 'G-FTGQ1MZXDT',
  );
}
